### ISSUE TITLE
createCustomTCPDF constructor parameter order

### ISSUE THREAD

**Issue by rlaszlo** [yii-joblo/pdffactory#1]
Hi!

I have a problem with the createCustomTCPDF method in the EPdfFactory.php

The default constructor order for the createTCPDF is 

```
$this->_tcpdf = new TCPDF($opt['orientation'],$opt['unit'],$opt['format'],$opt['unicode'],$opt['encoding'],$opt['diskcache'],$opt['pdfa']);
```

But in the case of createCustomTCPDF is

```
$this->_tcpdf = new $class($opt['format'], $opt['orientation'],$opt['unit'],$opt['unicode'],$opt['encoding'],$opt['diskcache'],$opt['pdfa']);
```

Is there any reason for the custom class to get the format parameter first?

Thanks for the answer!

**Comment by yii-joblo** [comment]
You're right, thanks.
This was a bug: fixed
